### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA


###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/

<> 2024-10-19T142105.200.json
<> 2024-10-17T185311.200.json
<> 2024-10-17T185106.200.json
<> 2024-10-17T185053.200.json
<> 2024-10-17T184718.200.json
<> 2024-10-17T174644.200.json
<> 2024-10-17T174425.200.json

###
POST http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/
Content-Type: application/json

{
    "name": "Wilki",
    "debutYear": 1991,
    "type": "BAND"
}

<> 2024-10-17T185320.200.json
<> 2024-10-17T185102.200.json

###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/c9111765-87f7-49c9-bf73-96d58d8e3275


###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/7e7ae796-759e-4075-bb41-b6b40cedfc18/avatar


###
PUT http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/a25b09aa-4c2b-4159-ab07-c1ca93108a4a/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="file.txt"

< C:\Users\oolle\OneDrive\Pulpit\Katalog\test.png
--WebAppBoundary--


###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/a25b09aa-4c2b-4159-ab07-c1ca93108a4a/avatar

<> 2024-10-17T174705.200.png
<> 2024-10-17T174655.404.html
<> 2024-10-17T174634.404.html


###
DELETE http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/bc72126e-9a5e-4304-a28a-df340312760f/avatar

###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres/songs

###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/songs/

###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres/7154908a-0aba-4967-814b-86740407acfb/songs

###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres

###
DELETE http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres/7154908a-0aba-4967-814b-86740407acfb

###
PUT http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres
Content-Type: application/json

{
  "genre": "TEST",
  "id": "0a9e3220-6f00-469a-ac30-b56b3de96759",
  "yearOfOrigin": 2002
}

###
PATCH http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres/0a9e3220-6f00-469a-ac30-b56b3de96759
Content-Type: application/json

{
  "genre": "Zmiana",
  "yearOfOrigin": 5000
}

###
PUT http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres/7154908a-0aba-4967-814b-86740407acfb/songs
Content-Type: application/json

{
  "title": "TEST",
  "length": 3.32,
  "premiereDate": "2002-05-10"
}

###
PATCH http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres/a835307d-d166-4201-adab-5c238e4f075d/songs/2a1855c3-5050-44cd-b76f-889bcbea798a
Content-Type: application/json

{
  "title": "TESTre",
  "length": 3.323,
  "premiereDate": "2002-05-11"
}

###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/musicGenres/a835307d-d166-4201-adab-5c238e4f075d/songs