### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA


###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/

###
POST http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/
Content-Type: application/json

{
    "name": "Wilki",
    "debutYear": 1991,
    "type": "BAND"
}

###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/c9111765-87f7-49c9-bf73-96d58d8e3275


###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/7e7ae796-759e-4075-bb41-b6b40cedfc18/avatar


###
PUT http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/c9111765-87f7-49c9-bf73-96d58d8e3275/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="file.txt"

< E:\testavatar\test.png
--WebAppBoundary--


###
GET http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/bc72126e-9a5e-4304-a28a-df340312760f/avatar


###
DELETE http://localhost:9080/demo-1.0-SNAPSHOT/api/authors/bc72126e-9a5e-4304-a28a-df340312760f/avatar